name: "CI Security Pipeline"

on:
  pull_request:
    branches: [ "dev" ]
    # Only run when there are code changes
    paths:
      - '**/*.ts'
      - '**/*.js'
      - '**/*.tsx'
      - '**/*.jsx'
      - 'package*.json'
      - 'prisma/**'
  push:
    branches: [ "dev" ]
  schedule:
    # Run weekly scan on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  ci-security:
    name: Lint, Build, Audit & Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Use only 'javascript' which covers TypeScript as well

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # Linting step - run on all events
    - name: Run ESLint
      run: npm run lint

    # Build verification step - run on all events
    - name: Build project
      run: npm run build

    # Dependency audit step - only on pushes and scheduled runs to save actions
    - name: Audit dependencies
      if: github.event_name == 'push' || github.event_name == 'schedule'
      run: npm audit --audit-level=moderate
      continue-on-error: true

    # Initialize CodeQL only for pushes to dev and scheduled runs
    - name: Initialize CodeQL
      if: github.event_name == 'push' || github.event_name == 'schedule'
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        # Use custom queries from the community
        queries: security-extended,security-and-quality

    # Autobuild for CodeQL (only when CodeQL is initialized)
    - name: Autobuild
      if: github.event_name == 'push' || github.event_name == 'schedule'
      uses: github/codeql-action/autobuild@v3

    # Perform CodeQL Analysis (only when CodeQL is initialized)
    - name: Perform CodeQL Analysis
      if: github.event_name == 'push' || github.event_name == 'schedule'
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"